#!/bin/sh
### BEGIN INIT INFO  
# Provides:          grabjpg 
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the /home/pi/clock
### END INIT INFO
case $1 in
    start)
        echo "starting  clock...."
        sudo /home/pi/clock &
    ;;
    stop)
        echo "stoping clock...."
        killall clock
    ;;
    *)
        echo "Usage: $0 (start|stop)"
    ;;

esac     